# Generated by Django 3.2.15 on 2022-10-26 18:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(choices=[('0', 'UAH'), ('1', 'USD'), ('2', 'EUR')], default='0', max_length=3)),
                ('curs', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
