# Generated by Django 3.2.15 on 2022-10-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('0', 'UAH'), ('1', 'USD'), ('2', 'EUR')], default='0', max_length=3),
        ),
    ]
