# Generated by Django 3.2.15 on 2022-12-24 10:49

from django.db import migrations


def populate(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.iterator():
        product.sku = str(product.id).split('-')[0]
        product.save(update_fields=('sku',))


def depopulate(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Product.objects.update(sku=None)


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0004_auto_20221103_1918'),
    ]

    operations = [
        migrations.RunPython(populate, depopulate),
    ]
